output "id" {
  value = azurerm_sentinel_data_connector_microsoft_defender_advanced_threat_protection.data_connector_microsoft_defender_atp.id
}

output "tenant_id" {
  value = azurerm_sentinel_data_connector_microsoft_defender_advanced_threat_protection.data_connector_microsoft_defender_atp.tenant_id
}

output "data_connector_microsoft_defender_atp" {
  value = azurerm_sentinel_data_connector_microsoft_defender_advanced_threat_protection.data_connector_microsoft_defender_atp
}